[reload]
command:template reload OPNsense/AppBlocker; /usr/local/sbin/pluginctl -s unbound restart
parameters:
type:script
message:Generating AppBlocker configuration
description:Reload AppBlocker settings

[start]
command:/usr/local/sbin/pluginctl -s unbound reload
parameters:
type:script
message:Restarting Unbound
description:Restart Unbound to apply AppBlocker settings

[restart]
command:/usr/local/sbin/pluginctl -s unbound restart
parameters:
type:script
message:Restarting Unbound
description:Restart Unbound

[status]
command:/usr/local/sbin/pluginctl -s unbound status
parameters:
type:script_output
message:Checking Unbound status
